### ISSUE TITLE
namespace clarity

### ISSUE THREAD

**Issue by himwho** [Supperware/ht-api-juce#2]
I was curious if it made more sense to use inline namespace declarations for each class declaration instead of using `using namespace juce;`

Running into a lot of ambiguity issues mixing and matching with other classes, especially around generic sounding ones like `juce::Button` and `juce::Label`

curious if you saw any issue in being a little more explicit with namespaces?

**Comment by bensupper** [comment]
Apologies for letting this one stew -- I don't see any problem with this at all for a public API, and it's a good idea. Merged.
